# uosc_danmaku 弹幕样式与行为配置
# 完整可选项参见 scripts/uosc_danmaku/modules/options.lua

#滚动弹幕的显示时间
scrolltime=15
#固定弹幕的显示时间
fixtime=5
#字体(名称两边不需要使用引号""括住)
fontname=sans-serif
#大小
fontsize=38
#阴影
shadow=0
#粗体
bold=yes
#透明度：0（完全透明）到 1（不透明）
opacity=0.7
#全部弹幕的显示范围(0.0-1.0)
displayarea=0.25
#描边 0-4
outline=1
#限制屏幕中同时显示的最大弹幕数量，0 表示不限制
max_screen_danmaku=0
#中文简繁转换。0-不转换，1-转换为简体，2-转换为繁体
chConvert=0
#指定弹幕屏蔽词文件路径(black.txt)，支持绝对路径和相对路径。文件内容以换行分隔
##支持 lua 的正则表达式写法
#blacklist_path=
